- name: Run wartest container
  community.general.docker_container:
    name: wartest
    image: "{{ image }}"
    state: started
    published_ports: "8081:8080"
    pull: yes
    login_username: "Jmarcus75"
    login_password: "{{ gitlab_token }}"
